---
name: idr0090-ashdown-malaria/screenA
version: 1

defaults:
  include: no
  type: string
  includeclient: yes
  visible: yes
  omitempty: yes

columns:

  - name: Experimental Condition [Parasite Line]
    clientname: Parasite Line
    include: yes

  - name: Control Type
    clientname: Control Type
    include: yes

  - name: Channels
    clientname: Channels
    include: yes


  ######################################################################
  # mapr groups
  ######################################################################

  - group:
      namespace: openmicroscopy.org/mapr/organism
      columns:
        - name: Characteristics [Organism]
          clientname: Organism
          include: yes

  - group:
      namespace: openmicroscopy.org/mapr/compound
      columns:
        - name: Compound 1 Name
          clientname: Compound Name
          include: yes
        - name: Compound PubChem URL
          clientname: Compound Name URL
          include: yes

  - group:
      namespace: openmicroscopy.org/mapr/compound
      columns:
        - name: Compound 2 Name
          clientname: Compound Name
          include: yes
        - name: Compound PubChem URL
          clientname: Compound Name URL
          include: yes

  - group:
      namespace: openmicroscopy.org/mapr/compound/supplementary
      columns:
        - name: Compound 1 Name
          clientname: Compound Name
          include: yes
        - name: Compound 1 PubChem CID
          clientname: PubChem CID
          include: yes
        - name: Compound 1 InChIKey
          clientname: InChIKey
          include: yes
        - name: Compound 1 Concentration (uM)
          clientname: Concentration (microMolar)
          include: yes
        - name: Compound Mechanism of Action (MoA)
          clientname: Mechanism of Action (MoA)
          include: yes

  - group:
      namespace: openmicroscopy.org/mapr/compound/supplementary
      columns:
        - name: Compound 2 Name
          clientname: Compound Name
          include: yes
        - name: Compound 2 PubChem CID
          clientname: PubChem CID
          include: yes
        - name: Compound 2 InChIKey
          clientname: InChIKey
          include: yes
        - name: Compound 2 Concentration (uM)
          clientname: Concentration (microMolar)
          include: yes
        - name: Compound Mechanism of Action (MoA)
          clientname: Mechanism of Action (MoA)
          include: yes


advanced:
  well_to_images: true
  ignore_missing_primary_key: yes
  primary_group_keys:
    - namespace: openmicroscopy.org/mapr/organism
      keys:
        - Organism
    - namespace: openmicroscopy.org/mapr/compound
      keys:
        - Compound Name
        - Compound Name URL
